### ISSUE TITLE
Integration with VisiData

### ISSUE THREAD

**Issue by aborruso** [frictionlessdata/framework#1010]
Hi,
I have discovered [VisiData](http://visidata.org/) and I think it could be a **great frictionlessdata reader and writer**.

It is a free, open-source tool that lets you quickly open, explore, summarize, and analyze datasets in your computer’s terminal and it's writter in Python. A good starting point is [this guide](https://jsvine.github.io/intro-to-visidata/) of Jeremy Singer Vine.

I'm not able to work on this kind of Python tasks and than I have written an [issue](https://github.com/saulpw/visidata/issues/237) in VisiData repo to ask to integrate datapackage in it. I have had this reply from @saulpw its creator:

> Sure, I like the idea! This should not be hard for someone familiar with the format to create a loader. If you know of anyone who would like to collaborate, I'm sure we can get something working in an afternoon (or two at most).

I think it could be "win, win, win". For VisiData, for dissemination and use of datapackages and for all open data community. 

Thank you

**Comment by roll** [comment]
@lwinfree 
I moved it to the framework

**Comment by roll** [comment]
DONE in `frictionless@5.10` - https://framework.frictionlessdata.io/docs/console/explore.html

**Comment by aborruso** [comment]
> DONE in `frictionless@5.10` - [framework.frictionlessdata.io/docs/console/explore.html](https://framework.frictionlessdata.io/docs/console/explore.html)

WOW, great news!!!!!

I have tried using 5.10 and I have. Is it right?

![image](https://user-images.githubusercontent.com/30607/225406544-8b51be92-f717-4c23-b3e3-9b48a30d8fae.png)

**Comment by roll** [comment]
Hi @aborruso,

I think the reason is the missing dependency - https://framework.frictionlessdata.io/docs/console/explore.html#installation

```
pip install frictionless[visidata]
```

**Comment by roll** [comment]
Also, the CLI output seems to be hiding the real reason "Please install 'frictionless[visidatta]'" - I created an issue for it https://github.com/frictionlessdata/framework/issues/1464

**Comment by aborruso** [comment]
> I think the reason is the missing dependency - [framework.frictionlessdata.io/docs/console/explore.html#installation](https://framework.frictionlessdata.io/docs/console/explore.html#installation)

I know, I have installed it.

I have:

- saul.pw/VisiData v2.11
- fr 5.10.0
- and installed `'frictionless[visidata]'`

**Comment by aborruso** [comment]
If I try using a file and not zenodo, it works

**Comment by roll** [comment]
Silly me =) `pip install frictionless[zenodo]` as well.

We need to fix this issue - https://github.com/frictionlessdata/framework/issues/1464 - so the installation message is not hidden

**Comment by aborruso** [comment]
Thanks, that's wonderful

I should add a note also below the zenodo example you have in visidata doc page.

Thank you
